# Introduction {-}

The National Health Service (NHS) in the United Kingdom is facing a 5% year-on-year increase in demand for urgent and emergency care services [@national_audit_office_nhs_2017]. In 2018/19, ambulance services in England provided a face-to-face assessment to nearly 7.9 million incidents, of which 5.4 million were conveyed to hospital [@nhs_england_ambulance_2019]. This non-conveyance rate of nearly 70% is occurring despite an increase in non-emergency cases and continues to place increasing demands on already crowded emergency departments (EDs), leading to decreased availability of ambulances as turnaround times at hospitals increase [@willett_addressing_2017]. ED overcrowding is a significant issue for patients, resulting in poorer quality of care, increased healthcare costs and potentially, increased mortality [@sun_effect_2013; @guttmann_association_2011; @bernstein_effect_2009; @richardson_increase_2006].

Yorkshire Ambulance Service NHS Trust (YAS) have been early adopters of initiatives to respond appropriately to the increase in non-emergency cases, with the introduction of advanced paramedics working in the role of Emergency Care Practitioners (ECP) since 2004 [@mason_developing_2003]. Even without selective dispatching, ECPs consistently have non-conveyance rates double that of other paramedics in the Trust. Since 2015, the specialist paramedic (SP) role has been introduced in YAS, with education comprising of a 1 year university program. However, during the time period of this study (2017--2019), YAS SP non-conveyance rates were around 37.5%, compared to the overall non-conveyance rate of 30%. In contrast, ECPs had non-conveyance rates of over 59% for all call categories.

In 2018, Health Education England (HEE) funded a pilot scheme to rotate paramedics into a range of healthcare settings, with the aim of improving patient care and relieving pressures on primary care, ambulance services and other parts of the NHS in a sustainable way [@turner_evaluation_2018]. A subsequent economic evaluation estimated that the rotating paramedics could save in the region of £275,000 per year in avoidable conveyance and subsequent admission to hospital compared to historic controls. However, data from Yorkshire included 5 ECPs who participated in the pilot and the analysis did not adjust for the difference in patient acuity between the pre- and post-placement phases [@health_education_england_rotating_2019].

The HEE pilot also presented an opportunity to further develop the decision-making of SPs, with the potential to deliver patient and cost-benefits that were anticipated when the role was created. This study aimed to evaluate whether a primary care placement appropriately increases the level and trend of non-conveyance decisions made by SPs compared to a matched control population of YAS paramedics in a cost-effective manner.

## Objectives {-}

The primary objective was to determine the change and trend in proportion of appropriate non-conveyance decisions by specialist paramedics who have completed a 10-week placement in a General Practitioner (GP) practice. The secondary objective was to compare the cost-effectiveness of specialist paramedics who have completed a 10-week placement in a GP practice compared to a matched control group of YAS paramedics.
