---
output:
  word_document: default
  html_document: default
---
# Discussion {-}

In this single NHS ambulance service study, we found a clinically important and statistical significant increase in appropriate non-conveyance of patients following a 10-week GP practice placement. In addition, this intervention proved to be cost saving compared to usual care. These results needs to be interpreted with caution, since they only include data from a single ambulance service with less than 10% of all paramedics currently in the role of SP. Training and experiential opportunities do vary between organisations, in part likely due to the piecemeal way in which the advanced practice roles have evolved for paramedics in the UK [@turner_evaluation_2018]. YAS has been commissioning the education of SPs with local Higher Education Institutions since 2014, with a focus on minor illness and injury, and long-term conditions, which is likely to resonate with other similar schemes [@hodge_maintaining_2018]. Furthermore, YAS have continued to work to develop their workforce model aligned to the College of Paramedics post-registration career framework since 2015 [@college_of_paramedics_post-registration_2018].

There were differences in the acuity and working impressions of patients between pre- and post-GP placement, supporting the choice of methodology for this study. Since cases were matched, it is possible to see how the control group of paramedics also achieved increased rates of appropriate non-conveyance when tasked to cases allocated a lower triage call category and NEWS risk category (Table \@ref(tab:table1)). However, even when accounting for case matching, intervention group SPs had a 35% improvement in appropriate non-conveyance compared to the control group. In addition, there were lower proportions of certain types of working impressions, such as acute cardiac and convulsions, and higher proportions for others, such as falls and minor injuries, reflecting dedicated tasking by SPs staffing a dispatch desk in EOC. It is possible that these proportions may have had a greater difference had the desk not closed in June 2019, perhaps reflecting the increased number of incidents attended by SPs in the final 3 months of the post-placement period. This may also correlate with the non-statistically significant drop in non-conveyance rates and increase in acuity of triage call categories seen at the same time.

Overall, SPs attended less cases in the post-placement phase. In addition to attending 999 calls, intervention group SPs also fulfilled other roles, including rotating back into GP surgeries (18% of post-placement hours) and staffing the desk in EOC (29.9%). This resulted in a drop in time responding to 999 calls from 84.4% pre-placement to 60.6% after (Table \@ref(tab:activity)). While availability for operational shifts reduced, the improved appropriate non-conveyance rates suggest that ambulance services should focus on EOC processes to maximise appropriate dispatching for specialist and advanced practice roles to 999 calls. 

The non-conveyance rates seen in this study are difficult to compare with other reported statistics, since the population included in this study is different to all emergency call activity. For example, in the intervention group's pre-placement phase, there was a higher proportion of category 1 and 2 calls (75--76.9%) compared to YAS figures reported nationally (64%), but a lower proportion post-placement, due to greater case selection with the introduction of the dedicated SP tasking desk [@nhs_england_ambulance_2018]. During the study period, YAS 'see and treat' rates were between 22.9--25.4% which was lower than the English average of 29.3--30.7% [@nhs_england_ambulance_2020]. 

An evaluation of the first phase of the rotating paramedic pilot reported non-conveyance rates of at least 70%, which mirrors the performance of rotating advanced paramedics in Wales [@association_of_ambulance_chief_executives_model_2019]. Two sites in the rotating paramedic pilot had non-conveyance rates in excess of 90%, however these schemes were primary care focused, rather than fully ambulance service based, highlighting the different models commissioned during the pilot.  Further evaluation is required to understand the most appropriate model for a paramedic rotation that benefits all parts of the system.

In YAS, the integration into the primary care teams during the Leeds rotation enabled the SPs to develop a greater understanding of the local healthcare system as they navigated pathways across community and acute care. This knowledge could then be utilised when the SPs rotated back into YAS and either responding to 999 calls or working in the EOC to identify appropriate 999 calls for an SP response. However, the impact of improved clinical knowledge and greater understanding of local pathways, and their effect on clinical practice and decision-making is uncertain, and requires further research. Despite this, the value of paramedics being afforded the opportunity to undertake a primary care placement has been demonstrated in this study and supports  the qualitative findings from the HEE evaluation. This suggests that support and education from GPs, an appreciation of primary care and other health and social care agencies and the opportunity to develop inter-service, multi-disciplinary relationships across the health and social care system, are beneficial to patient care [@health_education_england_rotating_2019].


## Limitations {-}

It is important to acknowledge this study's limitations. We used routine observational data rather than conducting a randomised-controlled trial for example, which was not possible since the rotation had already completed on commencement of this work. The outcome of this study, while patient focused, could not capture episodes where patients presented to other sectors of the healthcare system as a result of a complication of not being conveyed to hospital. In addition, identifying re-contacts, relied on identification of cases either by NHS number or a combination of patient name, age and incident location which may have been missing on subsequent calls. 

The number of missing working impression codes was not anticipated, and so no contingency was made in the methodology to account for this. While the sensitivity analysis showed that this is likely to have had a modest impact on our findings, in retrospect this study would have been more robust with a plan to take account of this.

Finally, it became apparent once the data was provided that determining the grade of paramedic with any certainty was not possible, which may have inflated the performance of the control group by inclusion of SPs who had not taken part in the HEE pilot.

# Conclusion {-}

In this single UK NHS ambulance service study, we found a clinically important and statistically significant increase in appropriate non-conveyance rates by specialist paramedics who had completed a 10-week GP rotation. This improvement persisted for the 12-month period following the rotation and demonstrated cost savings compared to usual care.


## Acknowledgements {-}

This work uses data provided by patients and collected by the NHS as part of their care and support. The authors would also like to thank the Yorkshire Ambulance service business intelligence team who collated the data used in this study.

## Contributors {-}

RP, TY and AH conceived and designed the study. RP obtained the research approvals and acts as guarantor for the paper. All authors drafted the manuscript and contributed substantially to its revision.

## Funding {-}

This paper presents independent research by the NIHR Applied Research Collaboration Yorkshire and Humber (ARC YH).

## Disclaimer {-}

The views expressed in this publication are those of the author(s) and not necessarily those of the National Institute for Health Research or the Department of Health and Social Care.

## Data sharing {-}

Permission has not been provided to make the original dataset available. However the scripts to undertake the analysis and a synthetic data set are available from the study GitHub repository:  [https://github.com/RichardPilbery/SPRAINED](https://github.com/RichardPilbery/SPRAINED).

